const express=require("express");
const hostController=require("../controller/hostController");
const adminController=require('../controller/adminController')
const {authentication}=require("../middleware/authentication")
const router=express.Router();
router.post('/hostLogin',hostController.hostLogin)
router.post('/hostProfile',hostController.hostProfile)
router.post('/EditProfile',authentication,hostController.EditProfile)
router.post('/AccountDeleted',authentication,hostController.AccountDeleted)
router.get('/fetchUser',authentication,hostController.fetchUser)
router.post('/viewUser',authentication,hostController.viewUser)
router.post('/faqAndHelp',authentication,adminController.faqAndHelp)
router.get('/fetchBooking',authentication,hostController.fetchBooking)
router.post('/ActivityAdded',authentication,hostController.ActivityAdded)
router.post('/editActivity',authentication,hostController.editActivity)
router.post('/deleteActivity',authentication,hostController.deleteActivity)
router.post('/subscriptionCreated',authentication,adminController.subscriptionCreated)
router.post('/subscriptionEdit',authentication,adminController.subscriptionEdit)
router.post('/subscriptionDeleted',authentication,adminController.subscriptionDeleted)
router.post('/BankDetails',authentication,hostController.BankDetails)
router.post('/bookingAction',authentication,hostController.bookingAction)
router.post('/UserDetails',authentication,hostController.UserDetails)
router.post('/contactForm',authentication,hostController.contactForm)
router.post('/adminLogin',adminController.adminLogin)
router.post('/adminProfile',authentication,adminController.adminProfile)
router.post('/EditAdminProfile',authentication,adminController.EditAdminProfile)
router.post('/adminAccountDeleted',authentication,adminController.adminAccountDeleted)
router.post('/fetchSingleBooking',authentication,hostController.fetchSingleBooking)
router.post('/userFetch',authentication,adminController.userFetch)
router.post('/editUserProfile',authentication,adminController.editUserProfile)
router.post('/deleteUserProfile',authentication,adminController.deleteUserProfile)
router.post('/fetchBooking',authentication,adminController.fetchBooking)
router.post('/viewBooking',authentication,adminController.viewBooking)
router.post('/deleteBooking',authentication,adminController.deleteBooking)
router.post('/updateBooking',authentication,adminController.updateBooking)
router.post('/hostFetch',authentication,adminController.hostFetch)
router.get('/dashBoardDetails',authentication,adminController.dashBoardDetails)
router.post('/userView',authentication,adminController.userView)
router.post('/fetchSubscription',authentication,adminController.fetchSubscription)
router.post('/SubscriptionView',authentication,adminController.SubscriptionView)
router.post('/faqEdit',authentication,adminController.faqEdit)
router.post('/faqDeleted',authentication,adminController.faqDeleted)
router.post('/fetchFaq',authentication,adminController.fetchFaq)
router.post('/faqView',authentication,adminController.faqView)
module.exports=router;