const express=require("express");
const userController=require("../controller/userController");
const {authentication}=require('../middleware/authentication')
const router=express.Router();
router.post('/signUp',userController.signUp)
router.post('/login',userController.login)
router.post('/profileSetUp',authentication,userController.profileSetUp)
router.post('/editUserProfile',authentication,userController.editUserProfile)
router.get('/fetchProfile',authentication,userController.fetchProfile)
router.post('/reSetPassword',authentication,userController.reSetPassword)
router.post('/forgetPassword',authentication,userController.forgetPassword)
router.post('/accountDelete',authentication,userController.accountDelete)
router.post('/BookingCreation',authentication,userController.BookingCreation)
router.post('/activityReview',authentication,userController.activityReview)
router.post('/disputeCreate',authentication,userController.disputeCreate)
router.post('/fetchBooking',authentication,userController.fetchBooking)
router.post('/activityCreated',authentication,userController.activityCreated)
router.post('/activityDetails',authentication,userController.activityDetails)
router.post('/countReview',authentication,userController.countReview)
router.post('/countRating',authentication,userController.countRating)
router.post('/paymentCOD',authentication,userController.paymentCOD)
router.post('/clearNotification',authentication,userController.clearNotification)
router.post('/reportCreation',authentication,userController.reportCreation)
router.post('/createStripe',authentication,userController.createStripe)
router.post('/createCard',authentication,userController.createCard)
router.get('/getToken',authentication,userController.getToken)
router.post('/cardList',authentication,userController.cardList)
router.post('/createPayment',authentication,userController.createPayment)
router.post('/createPaymentIntent',authentication,userController.createPaymentIntent)
router.post('/paymentHistroy',authentication,userController.paymentHistroy)
module.exports=router;