module.exports=(Sequelize,sequelize,DataTypes)=>
{
    return sequelize.define(
        "activityTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
               type:Sequelize.UUID,
               allowNull:true,
               references:
               {
                  model:"userTable",
                  key:"id"
               },
               onUpdate:"CASCADE",
               onDelete:"CASCADE"
            },
            hostId:
            {
               type:Sequelize.UUID,
               allowNull:true,
               references:
               {
                  model:"userTable",
                  key:"id"
               },
               onUpdate:"CASCADE",
               onDelete:"CASCADE"
            },
             DateAndTime:
             {
                type:DataTypes.STRING(),
                allowNull:true
             },
             Duration:
             {
                type:DataTypes.STRING(225),
                allowNull:true
             },
             hourlyRate:
             {
                type:DataTypes.STRING(225),
                allowNull:true
             },
             Tags:
             {
                type:DataTypes.STRING(225),
                allowNull:true
             },
             vibe:
             {
                type:DataTypes.STRING(225),
                allowNull:true
             },
             description:
             {
                type:DataTypes.STRING(225),
                allowNull:true
             },
             defaultCategory:
             {
               type:DataTypes.STRING(225),
               allowNull:true
             },
             fewWords:
             {
               type:DataTypes.TEXT(),
               allowNull:true
             },
             whatweDo:
             {
               type:DataTypes.TEXT(),
               allowNull:true
             },
           
        },
        {
            tableName:"activityTable"
        }
    )
}