module.exports=(Sequelize,sequelize,DataTypes)=>
{
    return sequelize.define(
        "reviewTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            bookingTd:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"bookingTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            rating:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0  
            },
            message:
            {
                type:DataTypes.TEXT(),
                allowNull:true
            },
            activityId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"activityTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            }
        },
        {
            tableName:"reviewTable"
        }
    )
}