module.exports=(Sequelize,sequelize,DataTypes)=>
{
    return sequelize.define(
        "transactionTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            bookingId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"bookingTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            hostId:
            {
                 type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            currency:
            {
                type:DataTypes.STRING(),
                allowNull:true
            },
            Amount:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            paymentStatus:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0  //1 for not paid and 2 for paid
            },
            paymentMethod:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0   //1 for cashonDelivery and 2 for netBanking payment
            },
            BankName:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            BranchName:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            AccountNumber:
            {
                type:DataTypes.INTEGER,
                allowNull:true
            },
            IFSC:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            }
        },
        {
            tableName:"transactionTable"
        }
    )
}