module.exports=(Sequelize,sequelize,DataTypes)=>
{
    return sequelize.define(
        "userTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            name:
            {
                type:DataTypes.STRING(100),
                allowNull:true
            },
            Email:
            {
                type:DataTypes.STRING(100),
                allowNull:true
            },
            password:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            phoneNumber:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            location:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            profileImage:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            otp:
            {
                type:DataTypes.INTEGER,
                allowNull:true
            },
            role:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0   //1 for member and 2 for host 3 for admin
            },
            age:
            {
                type:DataTypes.INTEGER,
                allowNull:true
            },
            tagLine:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            gender:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0  //1 for male and 2 for female
            },
            shortBio:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            interests:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            countryCode:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
           customerId:
            {
              type:DataTypes.STRING(),
              allowNull:true,
              defaultValue:null
            },
            socketId:
            {
                type:DataTypes.STRING(),
                allowNull:true
            }
        },
        {
            tableName:"userTable"
        }
    )
}